
[[constraint]]
  branch = "master"
  name = "github.com/golang/glog"

[[constraint]]
  branch = "master"
  name = "github.com/prometheus/common"

[[constraint]]
  branch = "6.1"
  name = "github.com/turbonomic/turbo-go-sdk"



[prune]
  go-tests = true
  unused-packages = true
